version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://jasur-webinar-demo-bucket/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://jasur-webinar-demo-bucket/'
